/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 20 03:43:26 GMT 2021
 */

package com.pg.cc.sb.core.TTest;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pg.cc.sb.core.TTest.Exam;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Exam_ESTest extends Exam_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Exam exam0 = new Exam();
      boolean boolean0 = exam0.canViewAnswer("123");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Exam exam0 = new Exam();
      boolean boolean0 = exam0.canViewAnswer((String) null);
      assertFalse(boolean0);
  }
}
